#pragma config(StandardModel, "SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void moveforward()
{
	motor[rightMotor] = 127;
	motor[leftMotor] = 127;
	wait1Msec(545);
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
}

void movebackward()
{
	motor[leftMotor] = -127;
	motor[rightMotor] = -127;
	wait1Msec(545);
}

void armupdown()
{
	motor[armMotor] = 127;
	wait1Msec(545);
	motor[armMotor] = -127;
	wait1Msec(545);
	motor[armMotor] = 0;
}

void turnforbac()
{
	motor[leftMotor] = 127;
	wait1Msec(545);
	motor[rightMotor] = -127;
	motor[leftMotor] = -127;
	wait1Msec(545);
}

void swingturnarm()
{
	motor[leftMotor] = 30;
	motor[rightMotor] = 127;
	wait1Msec(6750);
}

void swingturnarmopp()
{
	motor[rightMotor] = 30;
	motor[leftMotor] = 127;
	wait1Msec(6750);
}

void forbacupdown()
{
	motor[rightMotor] = 127;
	motor[leftMotor] = 127;
	motor[armMotor] = -127;
	wait1Msec(545);
	motor[rightMotor] = -127;
	motor[leftMotor] = -127;
	motor[armMotor] = 127;
	wait1Msec(545);
}

task main()
{
	repeat(8)
	{
		armupdown();
	motor[armMotor] = 0;
	}
	repeat(10)
	{
		moveforward();
		movebackward();
	}
	repeat(18)
	{
		turnforbac();
	}
	swingturnarm();
	swingturnarmopp();
	motor[rightMotor] = 127;
	motor[leftMotor] = 127;
	wait1Msec(2000);
	motor[rightMotor] = 127;
	motor[leftMotor] = 30;
	wait1Msec(2000);
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	repeat(8)
	{
		armupdown();
	}
	repeat(5)
	{
		motor[rightMotor] = 127;
		wait1Msec(3400);
	}

	repeat(16)
	{
		forbacupdown();
	}
	motor[armMotor] = 127;
	wait1Msec(400);
	motor[armMotor] = -127;
	wait1Msec(400);
}
